/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#2a2a2a',
        'inverse-on-surface': '#313030',
        'tertiary-container': '#b4b2b2',
        'tertiary-fixed': '#e5e2e1',
        'inverse-surface': '#e5e2e1',
        'surface-container-lowest': '#0e0e0e',
        'secondary-fixed-dim': '#c8c6c6',
        outline: '#99907c',
        'on-tertiary-fixed': '#1c1b1b',
        'on-primary-fixed': '#241a00',
        'surface-dim': '#131313',
        'primary-fixed': '#ffe088',
        'on-surface': '#e5e2e1',
        'on-secondary-container': '#b6b5b4',
        'on-secondary': '#303030',
        'surface-container-highest': '#353534',
        'primary-container': '#d4af37',
        background: '#131313',
        error: '#ffb4ab',
        'surface-container': '#201f1f',
        'inverse-primary': '#735c00',
        'on-secondary-fixed-variant': '#474747',
        'on-primary-container': '#554300',
        'surface-variant': '#353534',
        'surface-container-low': '#1c1b1b',
        'primary-fixed-dim': '#e9c349',
        'on-error': '#690005',
        'on-secondary-fixed': '#1b1c1c',
        'on-primary': '#3c2f00',
        'outline-variant': '#4d4635',
        'surface-bright': '#3a3939',
        surface: '#131313',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#574500',
        secondary: '#c8c6c6',
        primary: '#f2ca50',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-background': '#e5e2e1',
        'on-surface-variant': '#d0c5af',
        'on-tertiary-container': '#454544',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#e4e2e1',
        tertiary: '#d0cdcd',
        'on-tertiary': '#313030',
        'secondary-container': '#474747',
        'on-tertiary-fixed-variant': '#474746',
        'surface-tint': '#e9c349',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
